### ISSUE TITLE
Connecting Mastodon account where address doesn't match domain causes error

### ISSUE THREAD

**Issue by FediVideos** [liberapay/liberapay.com#2320] opened 2024-03-02 10:24 UTC
Just a headsup in case anyone is having trouble connecting Mastodon accounts with an address domain that doesn't match their instance web address: to connect the account to Liberapay you have to use the website domain in your address even if this is incorrect for your account address.

Here's an example:

Entering the address @account@example.com on the Mastodon instance social.example.com will not connect to Liberapay, even if this is your correct Mastodon address.

Entering the address @account@social.example.com on the Mastodon instance social.example.com will connect to Liberapay, even if it is not your correct Mastodon address.

It seems that Liberapay is unable to properly process accounts from Mastodon instances that use subdomains for the website but not their accounts.

**Comment by Changaco** [comment] 2024-03-03 10:33
Closing as a duplicate of #945.

**Closed by Changaco** 2024-03-03 10:33 UTC
