### ISSUE TITLE
Suggestion: option to transfer the donor's username to the recipient

### ISSUE THREAD

**Issue by tuxayo** [liberapay/liberapay.com#852] opened 2017-12-10 16:33 UTC
The donor could choose to let it's username be transferred to the recipient.

Use case:
https://en.liberapay.com/davidrevoy/
> Q: Can I get a credit written at the end of Pepper&Carrot if I donate via Liberapay ?
> A: No, I can't get access to your name/nickname here, it's a limitation of the platform but also a feature: your donation are totally anonymous to me.

**Comment by Changaco** [comment] 2017-12-10 16:38
This issue is a duplicate of #271.

**Closed by Changaco** 2017-12-10 16:38 UTC

**Comment by tuxayo** [comment] 2017-12-10 19:26
Thanks, I didn't manage to phrase a search query that would find it.
