### ISSUE TITLE
Funding donations with Paypal not working

### ISSUE THREAD

**Issue by haheute** [liberapay/liberapay.com#1246] opened 2018-09-19 21:14 UTC
I hope this is not a duplicate issue. I've chosen paypal to Fund my donations, selected 10 € and clicked the "initiate the payment" button.

It does some color change on the button (a bit lighter for some seconds) and nothing happens. 

Chromium console says: `liberapay.com/:1 Refused to send form data to 'https://www.paypal.com/' because it violates the following Content Security Policy directive: "form-action 'self'".`

edit:
It seemed as if nothing happened, but the "Ledger" shows all 4 attempts with 'preparing' and 'pending'.

**Comment by Changaco** [comment] 2018-09-20 07:36
I can reproduce locally with Chromium 69.

The [CSP bypass](https://github.com/liberapay/liberapay.com/blob/324/liberapay/utils/state_chain.py#L204-L222) isn't kicking in because the request is being redirected twice.

**Comment by Changaco** [comment] 2018-09-20 07:54
I've found a simple fix and applied it.

**Comment by haheute** [comment] 2018-09-20 08:10
Is the fix already in production?
What will happen with the "preparing/pending" charges in my Ledger? (remove them?)
Thanks a lot

**Comment by Changaco** [comment] 2018-09-20 09:20
Yes, the fix is in production. I'll mark the unfinished payments as "failed" later.

**Comment by haheute** [comment] 2018-09-20 09:45
I have tried again. The button seemed to work. 

Paypal has sent an email, which says that I have paid the money as _one amount_ to the receiver.

The donation is still: 

`13 hours ago | 13 hours ago | No: awaiting payment`

and there is an error message in the ledger:

```
donation to xxxxxxx (40 weeks of €0.25) — pending — error message: RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION | €10.00 |  
-- | -- | --
charge — succeeded
```

**Closed** 2018-09-21 07:08 UTC
Labels: Bug
