### ISSUE TITLE
Backers unable to pay

### ISSUE THREAD

**Issue by bbhorne** [liberapay/liberapay.com#1720] opened 2020-04-01 12:11 UTC
This seems to be a major bug as people are not able to sign up to back me and I only hear about it when there is a pre-existing relationship and the want-to-be backer gets in touch with me via other methods. The platform does not even notify me when someone fails to complete all the steps of your process, nor is there a detailed error message to let either of us know where the issue is occurring. 

![yyOQ3TEx](https://user-images.githubusercontent.com/13185201/78135568-77f74980-73f8-11ea-8d3b-5aecc6c92581.png)

(the error message thrown up by the platform is incorrect, as the bank account my backer was trying to use to pay me is a Euro bank account)

**Comment by Changaco** [comment] 2020-04-01 12:25
Closing as a duplicate of #1525.

The error message is from Stripe and is about your Stripe account, not your backer's bank account. Yes, it's confusing.

**Closed by Changaco** 2020-04-01 12:25 UTC

**Comment by Changaco** [comment] 2020-04-04 07:50
@bbhorne The error message shown to the donor will now be: “The payment processor (Stripe) isn't able to process Euro direct debits for this recipient yet. Please retry with a different payment method.”
