### ISSUE TITLE
Implement k-anonymity for password-based sign up.

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#1795] opened 2020-06-14 12:25 UTC
It would be nice to cross-check passwords in breaches during the sign-up and password-reset process. This is in similar vein to #1001: the goal being to ensure good password hygiene.

Resources:

- https://haveibeenpwned.com/API/v2#PwnedPasswords
- https://en.wikipedia.org/wiki/K-anonymity#Hash_Based_k-Anonymity

**Comment by Changaco** [comment] 2020-06-14 13:06
Duplicate of #986.

**Closed by Changaco** 2020-06-14 13:06 UTC
Labels: Defense

**Comment by EdOverflow** [comment] 2020-06-14 13:08
![](https://media.giphy.com/media/Ra1bmpxpsppNC/giphy.gif)
