### ISSUE TITLE
"" is not a valid number

### ISSUE THREAD

**Issue by jibe-b** [liberapay/liberapay.com#1733] opened 2020-04-09 08:28 UTC
Hi, I entered my IBAN to renew donations and next page showed :

```URL: https://liberapay.com/<USER>/giving/pay/stripe/?beneficiary=<ID_1,ID2>&method=sdd
Method: POST
Referer: b'https://liberapay.com/<USER>/giving/pay/stripe/?beneficiary=<ID_1,ID2>&method=sdd'
Response code: 400
Response message: '"" is not a valid number.'```

**Comment by jibe-b** [comment] 2020-04-09 08:30
And it was easy to figure it out:

the value of the payment was not set.

![Screenshot from 2020-04-09 10-29-24](https://user-images.githubusercontent.com/6146483/78874659-0436eb80-7a4d-11ea-9e5e-9d7e5e801005.png)

I guess the control should be done directly in the form.

Thanks for the amazing work you do!

**Comment by Changaco** [comment] 2020-04-09 09:27
This issue is a duplicate of #1696.

**Closed by Changaco** 2020-04-09 09:27 UTC

**Comment by jibe-b** [comment] 2020-04-09 09:30
Thanks @Changaco!
