### ISSUE TITLE
Invitation alert does not disappear after accepting it

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#260] opened 2016-04-09 14:58 UTC
![image](https://cloud.githubusercontent.com/assets/7630875/14404370/ddb02fa8-feae-11e5-9e62-019fa9d388ac.png)

I am already a part of liberapay team, but the alert does not automatically disappear.

**Comment by Changaco** [comment] 2016-04-09 15:16
Duplicate of #133. ;-)

**Closed by Changaco** 2016-04-09 15:16 UTC
