### ISSUE TITLE
Incorrect language used for email

### ISSUE THREAD

**Issue by iangilfillan** [liberapay/liberapay.com#951] opened 2018-01-24 20:09 UTC
Two of us have access to an organizational account. When the account was set up, the language selected on https://liberapay.com/ORGANIZATION/edit was Finnish. I changed this to English, and currently on the website everything appears in English. However, the email received (announcing our received payment) was in Finnish. I cannot see a way to change this. The only two language options appear to be the "Switch to another language" option in the top bar, and the current language option at https://liberapay.com/ORGANIZATION/edit and both are English.
Either the email is using an old setting, and needs to accept the current default, or the option to change language is well hidden (I've gone through the options carefully), and needs to be made more visible, for example on the https://liberapay.com/ORGANIZATION/emails/ page.

There is also county of residence, and country of nationality, both set to Finnish, but these should not affect the language used in the emails.

**Comment by Changaco** [comment] 2018-01-24 23:09
This issue is a duplicate of #252. The language used for emails is based on the languages requested by the browser at the time the account was created.

**Closed** 2018-02-10 12:42 UTC
