### ISSUE TITLE
One-time payments

### ISSUE THREAD

**Issue by rubyFeedback** [liberapay/liberapay.com#1933] opened 2020-12-14 16:05 UTC
Would it be possible to enable one-time payments?

The reason why I dislike time-based recurring donations is because of my bad brain remembering
stuff. I also miss lots of notifications in general (I rarely read emails, for example), so it would much
simplify if there would be an option for once-only transactions.

**Comment by Changaco** [comment] 2020-12-15 09:02
Liberapay will support one-time donations, but I don't know when. I'm closing this issue as a duplicate of #415.

**Closed by Changaco** 2020-12-15 09:02 UTC
