### ISSUE TITLE
[FEATURE REQUEST] Add a dark mode in the website

### ISSUE THREAD

**Issue by Panquesito7** [liberapay/liberapay.com#2060] opened 2021-08-17 01:28 UTC
Currently, I use Dark Reader to have many sites in dark mode. One of them is Liberapay. Nowadays, many people are using dark themes in their systems. Also, the light theme might be annoying for some people (like me).
It'd be great if we could add a dark theme to the website (with a toggle button for the light/dark theme).

Let me know what do you think. Thanks. 🙂

**Comment by Changaco** [comment] 2021-08-17 06:40
This issue is a duplicate of #1592.

**Closed by Changaco** 2021-08-17 06:40 UTC
