### ISSUE TITLE
Try to add a GitHub repository from a Organization

### ISSUE THREAD

**Issue by angelcervera** [liberapay/liberapay.com#1721] opened 2020-04-01 16:54 UTC
When I try to add a repo from GitHub, only the repos under my user account are listed.
I want to add a project that is under a GitHub organization. I'm the owner.
Is there a way to do it?

**Comment by Changaco** [comment] 2020-04-01 20:49
Currently a GitHub organization and its repositories can only be attached to a [team](https://liberapay.com/about/teams) or organization Liberapay account.

I'm closing this issue as a duplicate of #1423.

**Closed by Changaco** 2020-04-01 20:49 UTC
