### ISSUE TITLE
MFA Configuration.

### ISSUE THREAD

**Issue by di-org** [liberapay/liberapay.com#2145] opened 2022-04-17 20:15 UTC
I have not been able to locate a section of your website to configure MFA on my account.  Is that possible?  If not, I'd like to submit that feature request for a TOTP solution.

Thanks!

**Comment by Changaco** [comment] 2022-04-18 08:21
Multi-Factor Authentication isn't supported. I'm closing this issue as a duplicate of #926.

**Closed by Changaco** 2022-04-18 08:21 UTC
