### ISSUE TITLE
Add /on/Gitlab

### ISSUE THREAD

**Issue by gjhklfdsa** [liberapay/liberapay.com#1521] opened 2019-06-16 05:23 UTC
**Feature**: Add /on/Gitlab

**What is Gitlab?**
Gitlab is a very popular code hosting website.
https://www.wikipedia.org/wiki/GitLab

**What do you want to happen?**
Currently you can go to "https://liberapay.com/on/[platform]/[platform_user]/" to pledge money in case somebody does join Liberapay. Currently this feature is only available for Bitbucket, Github, and Twitter. My feature request is to add Gitlab to that mix.

**Does this already work?**: Nope, https://archive.fo/vVFvK

**Comment by Changaco** [comment] 2019-06-16 06:46
Closing as a duplicate of #1154.

**Closed by Changaco** 2019-06-16 06:46 UTC
