### ISSUE TITLE
Nearly all the Stripe transactions are partially refunded

### ISSUE THREAD

**Issue by unfa** [liberapay/liberapay.com#2132] opened 2022-02-28 12:31 UTC
Hey - It's strange but or every donation I receive via Liberapay and Stripe I get "partially refunded" with like 0.5 EUR sent back. It seems automatic, do you know what that is?

![image](https://user-images.githubusercontent.com/491704/155983926-e4805d4d-6645-4cdf-a13c-6c705ddebec1.png)

**Comment by Changaco** [comment] 2022-02-28 13:34
The partial refunds are how Liberapay recovers Stripe's fee on single-recipient payments.

**Comment by Changaco** [comment] 2022-02-28 13:34
Closing as a duplicate of #1987.

**Closed by Changaco** 2022-02-28 13:34 UTC

**Comment by unfa** [comment] 2022-02-28 13:43
I see. Is that a... loophole?

**Comment by Changaco** [comment] 2022-03-01 09:55
More of a workaround than a loophole.

**Comment by LiamDawe** [comment] 2022-05-15 15:50
Sorry to drag this up but is this actually documented anywhere be Liberapay?
