### ISSUE TITLE
Handle one time tip.

### ISSUE THREAD

**Issue by aloisdg** [liberapay/liberapay.com#1059] opened 2018-04-10 12:50 UTC
Hello,

I would love to have a service beside https://www.leetchi.com/ or https://www.lepotcommun.fr/.
As a liberapay user, it could be done by starting a donation and stop it after one iteration. I think it could be improve.

Maybe someting like this?

![oentime](https://user-images.githubusercontent.com/3449303/38557736-3ba0d0d6-3cce-11e8-9fcb-48ce07846247.PNG)

I am sad to see [solidary donation campaign](https://www.leetchi.com/fr/Cagnotte/31978353/a8a95db7) on this kind of website...

Thank you

**Comment by Changaco** [comment] 2018-04-10 13:05
This issue is a duplicate of #415.

**Closed by Changaco** 2018-04-10 13:05 UTC
