### ISSUE TITLE
Income who are not easy divisible are wrong

### ISSUE THREAD

**Issue by Zatalyz** [liberapay/liberapay.com#463] opened 2016-12-22 12:02 UTC
A little bug, but it can be problematic in team. Excellent example here : https://en.liberapay.com/Khaganat/income/

Team have 0,85€/week and 7 people. It divide in 7 ( 0,121428 etc), rounded to the decimal point top (0,13), and the last member have less (0,85-(6*0,13)=0.07). Because people are alphabetical ordered, it's for me ;) but, also, it's always the same people who haven't got all of his part. 

Better to rounded to the decimal point lower and so have "Leftover". And when leftover is divisible by the number of people, it's shared. 

Example : like now, Team have 0,85€/week and 7 people. 0.85/7 and rounded lower = 0,12, rest 1 centime. So leftover have 1 centime per week ; after 7 week, if they are always 7 people in the team, all people have 1 centime in addition. And all people have the same income if all have the same part :)

**Comment by Changaco** [comment] 2016-12-22 18:52
Originally this was supposed to be solved by processing team takes in random order, so it wouldn't be the same member who gets less each time, but this is linked to #434 and I haven't gotten around to that yet.

Keeping track of unused team income is also a good idea though. I've been planning to implement it as well, but more for #81.

**Comment by lewjs16** [comment] 2021-04-08 20:12
I was wondering if this issue was still open & needed to be fixed. I am interested in working on it/looking into it further!

**Comment by Changaco** [comment] 2021-04-09 08:10
I think this can still happen. I recommend adding a test in the `tests/py/test_payday.py` file to reproduce the problem: a team with €0.85 income and 7 members each taking €1. This should confirm that the `Payday.resolve_takes()` function needs to be improved.

The issue can probably be fixed by replacing the simplistic `takes_ratio` ([payday.py#L472-L477](https://github.com/liberapay/liberapay.com/blob/593/liberapay/billing/payday.py#L472-L477)) with a call to the generic `resolve_amounts()` function ([common.py#L493](https://github.com/liberapay/liberapay.com/blob/593/liberapay/payin/common.py#L493)).

**Comment by mhogara** [comment] 2021-04-14 01:21
We’ve been working on this issue and have successfully made a test to reproduce the problem and have it failing on the current version of the code. 

Fixing the issue itself has been a bit more difficult though; we are trying to call `resolve_amounts()`(common.py#L493), but are not sure what exact arguments to pass in. As of right now, we think that `available_amount` would be `fuzzy_income_sum` and `convergence_amounts` could be a dictionary of IDs or indices and corresponding takes. However, we aren’t sure what should be passed in for `base_amounts`. 

Also in the context of payday.py#L472-L477 what exactly would `resolve_amounts` be returning to? Any advice would be helpful.

**Comment by Changaco** [comment] 2021-04-14 14:00
> As of right now, we think that `available_amount` would be `fuzzy_income_sum` and `convergence_amounts` could be a dictionary of IDs or indices and corresponding takes. However, we aren’t sure what should be passed in for `base_amounts`.

Hmm… Take amounts are maximums, but `resolve_amounts` is designed to always distribute the entire available amount, so we have to give it an amount that's never greater than the sum of the takes. This should work:

```python
resolved_takes = resolve_amounts(
    min(fuzzy_income_sum, fuzzy_takes_sum),
    {take.member: take.amount for take in takes}
)
```

**Comment by lewjs16** [comment] 2021-04-15 05:49
For testing purposes, is there an easy way to only run test_payday.py without running the full "make tests" command? On our computers the "make tests" command takes quite a bit of time, and we were trying to find a way to streamline our debugging process! Any advice would be helpful, thank you!

**Comment by Changaco** [comment] 2021-04-15 06:55
You can do `make pytest PYTEST=payday` to run only the tests in `test_payday.py`, or make sure that your test is failing and do `make pytest-re` to rerun only that test.

**Comment by lewjs16** [comment] 2021-04-15 20:41
Following the example given & using the resolved_amounts function, the end result would be that one person would receive 0.01 extra every week (versus having one person with 0.06 less than everyone else). We were wondering if this is the desired outcome because if everyone were to get equal parts and then store leftovers, we would probably need to write another function to implement this outcome. Let us know what option/outcome you would prefer!

**Comment by Changaco** [comment] 2021-04-17 07:29
Giving an extra cent to one of the members is a simple and acceptable solution. Ideally the cent should go to a different member every week.

**Closed** 2021-05-09 07:46 UTC
Labels: Bug, Payday
