### ISSUE TITLE
Connecting account to GitLab requests way too many permissions

### ISSUE THREAD

**Issue by taktoa** [liberapay/liberapay.com#892] opened 2017-12-22 14:05 UTC
If I want to connect my liberapay account to my GitLab account, I have to give liberapay permissions to do arbitrary things as me on GitLab, which I am not comfortable with for what should be obvious reasons.

**Comment by andersjohansson** [comment] 2018-02-02 18:00
I felt the same. Is the case that the permissions in the gitlab API are not granular enough? From what I could find in the documentation, these are the permission levels: https://gitlab.com/help/user/profile/personal_access_tokens.md#limiting-scopes-of-a-personal-access-token (also applies to OAuth, I think, but not documented there: https://gitlab.com/help/api/oauth2.md)

But perhaps it would be sufficient for liberapay to get access with a `read_user` scope and then would `GET /projects` return only public projects, which should be all that is needed? https://gitlab.com/help/api/projects.md#list-all-projects

I don't really have enough insight into how this works and haven't tested anything, but I noticed that the gitlab API v3 ([which liberapay uses?]( https://github.com/liberapay/liberapay.com/blob/master/liberapay/elsewhere/gitlab.py#L27)) should be deprecated (and they're moving to graphQl), so maybe this has to be looked into soon also because of that:

**Comment by Changaco** [comment] 2018-04-02 15:47
I've just tried the `read_user` scope, it doesn't allow us to get the list of the user's public repositories.

```
DEBUG:urllib3.connectionpool:https://gitlab.com:443 "GET /api/v4/projects?owned=true&visibility=public&order_by=last_activity_at&per_page=100 HTTP/1.1" 403 140
ERROR:liberapay.elsewhere:gitlab.com responded with 403:
{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api"}
```

**Comment by danShumway** [comment] 2018-04-02 15:54
That seems odd to me - if the repositories are public, Liberapay shouldn't even need a permission. It can't be a security restriction since regular scraping would work just as well.

I wonder if this is a bug on Gitlab's side of things?

[Documentation](https://gitlab.com/help/api/projects.md#list-user-projects) says that when accessed woithout authentication, only public projects should be returned. But public projects would be enough, right?

**Comment by Changaco** [comment] 2018-04-02 15:59
I've also tried the `/users/:user_id/projects` endpoint, it returns the same error.

**Comment by danShumway** [comment] 2018-04-02 16:04
Maybe I'm missing something but I can't think of what they're even protecting; all the information is publicly accessible.

I can do a little bit of experimentation once I get some free time today or tomorrow. If I can confirm, want me to head over and file a bug on their end?

**Comment by Changaco** [comment] 2018-04-02 16:05
GitLab's API has never handled permissions well, we've been waiting for more than 2 years for <https://gitlab.com/gitlab-org/gitlab-ce/issues/13795>.

**Comment by danShumway** [comment] 2018-04-02 16:07
Oof. That's a little bit disappointing.

**Comment by lyndsysimon** [comment] 2018-04-04 21:01
I ran into the same issue today. What I did was grant access then revoke the key on GitLab's side.

If you do that, make sure that you import your repositories first, otherwise Liberapay throws a 503 when asked to do so.

**Comment by IzzySoft** [comment] 2018-06-24 13:09
You probably want to watch/join/thumb-up [this issue on GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/45001) then:

> Proposal
>
> Allow the creation of Group Level access tokens which can have permissions to:
>
> *    Group configuration, such as listing all the projects
> *    Projects specifically with varying degrees of authority, READ-ONLY, UPDATE-CONFIGURATION, PUSH, etc...

For this issue here, it would be the READ-ONLY authority which is needed.

**Comment by IzzySoft** [comment] 2018-06-29 06:34
Note that the first GitLab issue I've linked got closed in favor of two split-offs. The relevant one here is [Limit the API scope of Personal Access Tokens](https://gitlab.com/gitlab-org/gitlab-ce/issues/41165).

**Comment by Changaco** [comment] 2019-02-05 11:02
I've found a way to work around GitLab's weird API permissions to access the public information we need.

**Closed** 2019-02-06 08:33 UTC
Labels: Elsewhere

**Comment by lyndsysimon** [comment] 2019-06-05 14:39
Any chance you could write up a very brief summary of your workaround? This is a common complaint with many services.

**Comment by Changaco** [comment] 2019-06-05 15:05
The solution is to request public data without sending any kind of authentication. If we send a user session token or an app session token then we get a 403 error, but when we make an "anonymous" request it works.
