### ISSUE TITLE
Error starting the dev environment on Docker

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1304] opened 2018-10-30 07:13 UTC
I still have a new error when trying to launch Liberapay from the current master branch:

```
$ docker-compose build
db uses an image, skipping
Building web
Step 1/11 : FROM debian:9
 ---> 3bbb526d2608
Step 2/11 : RUN apt-get update &&     apt-get install -y build-essential wget libpq-dev libffi-dev python-dev postgresql-client &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a54d7f715ea7
Step 3/11 : RUN wget -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py && python /tmp/get-pip.py
 ---> Using cache
 ---> 94606304a520
Step 4/11 : ADD ./requirements_base.txt /requirements/pip/base.txt
 ---> Using cache
 ---> 47c78c844e7a
Step 5/11 : RUN pip install --require-hashes -r /requirements/pip/base.txt
 ---> Using cache
 ---> 0f612194b8f1
Step 6/11 : ADD ./requirements_dev.txt /requirements/pip/dev.txt
 ---> 6d9b1d8a0a28
Step 7/11 : RUN pip install --require-hashes -r /requirements/pip/dev.txt
 ---> Running in 47d65d0ef0b6
Collecting honcho==0.5.0 (from -r /requirements/pip/dev.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e2/64/0202ee691bc9cf91121150da6d6896131fd42c9d658e9c7af2786423d1ff/honcho-0.5.0.tar.gz
Collecting gunicorn==19.6.0 (from -r /requirements/pip/dev.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/72/de/ec28a64885e0b390063379cca601b60b1f9e51367e0c76030ac8a5cddd5e/gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
Collecting pyOpenSSL==17.0.0 (from -r /requirements/pip/dev.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/8c/b7/0048adbf09ad93f571e70fb3100e696d4711cdcbfe38161690d716a5ed35/pyOpenSSL-17.0.0-py2.py3-none-any.whl (51kB)
Collecting cryptography==2.3.1 (from -r /requirements/pip/dev.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/87/e6/915a482dbfef98bbdce6be1e31825f591fc67038d4ee09864c1d2c3db371/cryptography-2.3.1-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
Collecting asn1crypto==0.22.0 (from -r /requirements/pip/dev.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/97/ba/7e8117d8efcee589f4d96dd2b2eb1d997f96d27d214cf2b7134ad8acf6ab/asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
Collecting enum34==1.1.6 (from -r /requirements/pip/dev.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: ipaddress==1.0.18 in /usr/local/lib/python2.7/dist-packages (from -r /requirements/pip/dev.txt (line 36)) (1.0.18)
Collecting ndg-httpsclient==0.4.2 (from -r /requirements/pip/dev.txt (line 39))
  Downloading https://files.pythonhosted.org/packages/a2/a7/ad1c1c48e35dc7545dab1a9c5513f49d5fa3b5015627200d2be27576c2a0/ndg_httpsclient-0.4.2.tar.gz
Collecting packaging==16.8 (from -r /requirements/pip/dev.txt (line 41))
  Downloading https://files.pythonhosted.org/packages/87/1b/c39b7c65b5612812b83d6cab7ef2885eac9f6beb0b7b8a7071a186aea3b1/packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing==2.2.0 (from -r /requirements/pip/dev.txt (line 44))
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL==17.0.0->-r /requirements/pip/dev.txt (line 9)) (1.8.0)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography==2.3.1->-r /requirements/pip/dev.txt (line 12)) (2.5)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography==2.3.1->-r /requirements/pip/dev.txt (line 12)) (1.9.1)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.7->cryptography==2.3.1->-r /requirements/pip/dev.txt (line 12)) (2.17)
Building wheels for collected packages: honcho, ndg-httpsclient
  Running setup.py bdist_wheel for honcho: started
  Running setup.py bdist_wheel for honcho: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d0/30/bc/1bfeeeb5e0327426729f9dd3513010afe41006b8892ef6a20f
  Running setup.py bdist_wheel for ndg-httpsclient: started
  Running setup.py bdist_wheel for ndg-httpsclient: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/0c/2a/de/55f5148b0783d715a1703e380b84765123d72f02be69dff36e
Successfully built honcho ndg-httpsclient
Installing collected packages: honcho, gunicorn, enum34, asn1crypto, cryptography, pyOpenSSL, ndg-httpsclient, pyparsing, packaging
Successfully installed asn1crypto-0.22.0 cryptography-2.3.1 enum34-1.1.6 gunicorn-19.6.0 honcho-0.5.0 ndg-httpsclient-0.4.2 packaging-16.8 pyOpenSSL-17.0.0 pyparsing-2.2.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 47d65d0ef0b6
 ---> 4671391f6c6a
Step 8/11 : ADD ./requirements_tests.txt /requirements/pip/tests.txt
 ---> f2f62341e309
Step 9/11 : RUN pip install --require-hashes -r /requirements/pip/tests.txt
 ---> Running in d3de74b42318
Collecting py==1.4.31 (from -r /requirements/pip/tests.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/19/f2/4b71181a49a4673a12c8f5075b8744c5feb0ed9eba352dd22512d2c04d47/py-1.4.31-py2.py3-none-any.whl (81kB)
Collecting pytest==2.8.7 (from -r /requirements/pip/tests.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/b2/14/5028e88e6023a6c7621cfafe30575d7d0aa42758d9fef78a3ef4238c3716/pytest-2.8.7-py2.py3-none-any.whl (151kB)
Collecting coverage==3.7.1 (from -r /requirements/pip/tests.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/09/4f/89b06c7fdc09687bca507dc411c342556ef9c5a3b26756137a4878ff19bf/coverage-3.7.1.tar.gz (284kB)
Collecting cov-core==1.15.0 (from -r /requirements/pip/tests.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/4b/87/13e75a47b4ba1be06f29f6d807ca99638bedc6b57fa491cd3de891ca2923/cov-core-1.15.0.tar.gz
Collecting pytest-cov==1.8.1 (from -r /requirements/pip/tests.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/11/4b/b04646e97f1721878eb21e9f779102d84dd044d324382263b1770a3e4838/pytest-cov-1.8.1.tar.gz
Collecting execnet==1.3.0 (from -r /requirements/pip/tests.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/1a/77/f390aa1ee13b03ba16fb7fc0829c1caa9fccba01b7017b1a0c52f846440b/execnet-1.3.0-py2.py3-none-any.whl
Collecting pytest-cache==1.0 (from -r /requirements/pip/tests.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/d1/15/082fd0428aab33d2bafa014f3beb241830427ba803a8912a5aaeaf3a5663/pytest-cache-1.0.tar.gz
Collecting mccabe==0.3.1 (from -r /requirements/pip/tests.txt (line 25))
  Downloading https://files.pythonhosted.org/packages/84/75/d7966b7280635e96a243d27ca39e5954e9af632a36a4e8eee44660e53540/mccabe-0.3.1-py2.py3-none-any.whl
Collecting pep8==1.7.0 (from -r /requirements/pip/tests.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/8a/cb/7d0fdca7e03f997945fb1bd60a8ddfea5c51229b865c470b4f7a64619d20/pep8-1.7.0-py2.py3-none-any.whl (41kB)
Collecting pyflakes==1.2.3 (from -r /requirements/pip/tests.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/74/55/98f59358be6d7240ba546b8a74813cc21841a9145a0c1a3a7998f50acbe7/pyflakes-1.2.3-py2.py3-none-any.whl (209kB)
Collecting flake8==2.5.5 (from -r /requirements/pip/tests.txt (line 34))
  Downloading https://files.pythonhosted.org/packages/01/f6/2b87406d83aacb6d1fa9acf2c7e3752f59020ebb1b1c9f8adc811d1ea6f0/flake8-2.5.5-py2.py3-none-any.whl
Collecting mock==1.0.1 (from -r /requirements/pip/tests.txt (line 38))
  Downloading https://files.pythonhosted.org/packages/a2/52/7edcd94f0afb721a2d559a5b9aae8af4f8f2c79bc63fdbe8a8a6c9b23bbe/mock-1.0.1.tar.gz (818kB)
Collecting PyYAML==3.12 (from -r /requirements/pip/tests.txt (line 42))
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
Collecting wrapt==1.10.11 (from -r /requirements/pip/tests.txt (line 49))
  Downloading https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
Collecting vcrpy==1.9.0 (from -r /requirements/pip/tests.txt (line 51))
  Downloading https://files.pythonhosted.org/packages/8d/45/4cad93f42c5a2a33105db3ef960970af5e1ac5c9206142d97a5bd23a8d76/vcrpy-1.9.0-py2.py3-none-any.whl
Collecting fake-factory==0.3.2 (from -r /requirements/pip/tests.txt (line 55))
  Downloading https://files.pythonhosted.org/packages/de/38/748a54953a65fbb970d5619bef360819ab7f8cd5d3fbbb5092df03dde01f/fake-factory-0.3.2.tar.gz (100kB)
Requirement already satisfied: contextlib2; python_version in "2.7, 3.1, 3.2" in /usr/local/lib/python2.7/dist-packages (from vcrpy==1.9.0->-r /requirements/pip/tests.txt (line 51)) (0.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from vcrpy==1.9.0->-r /requirements/pip/tests.txt (line 51)) (1.8.0)
Building wheels for collected packages: coverage, cov-core, pytest-cov, pytest-cache, mock, PyYAML, wrapt, fake-factory
  Running setup.py bdist_wheel for coverage: started
  Running setup.py bdist_wheel for coverage: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/68/58/66/f1fc9afad272df0df0fa38cdef34ee2d5d8d6a85f4eb5acab5
  Running setup.py bdist_wheel for cov-core: started
  Running setup.py bdist_wheel for cov-core: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/34/b4/08/2eb04c831f579f1d77e5150eea39fbded92bce3ed3d55f088a
  Running setup.py bdist_wheel for pytest-cov: started
  Running setup.py bdist_wheel for pytest-cov: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f5/40/04/e41439dccc3146d774a84fb2003ce4b056891e3e747db2c4b9
  Running setup.py bdist_wheel for pytest-cache: started
  Running setup.py bdist_wheel for pytest-cache: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e4/9e/28/59d0a23800e49808f17920c5922252c661966ca4a36db5ee38
  Running setup.py bdist_wheel for mock: started
  Running setup.py bdist_wheel for mock: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/7e/72/92/744b532c779242b57aab4bcba80c312b30c069bbd60025e7e6
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
  Running setup.py bdist_wheel for wrapt: started
  Running setup.py bdist_wheel for wrapt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/48/5d/04/22361a593e70d23b1f7746d932802efe1f0e523376a74f321e
  Running setup.py bdist_wheel for fake-factory: started
  Running setup.py bdist_wheel for fake-factory: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/aa/54/9d/0ccc9a3dc83da773794acb92321e54d9679cb4d1f576cbc653
Successfully built coverage cov-core pytest-cov pytest-cache mock PyYAML wrapt fake-factory
flake8 2.5.5 has requirement pyflakes<1.1,>=0.8.1, but you'll have pyflakes 1.2.3 which is incompatible.
Installing collected packages: py, pytest, coverage, cov-core, pytest-cov, execnet, pytest-cache, mccabe, pep8, pyflakes, flake8, mock, PyYAML, wrapt, vcrpy, fake-factory
Successfully installed PyYAML-3.12 cov-core-1.15.0 coverage-3.7.1 execnet-1.3.0 fake-factory-0.3.2 flake8-2.5.5 mccabe-0.3.1 mock-1.0.1 pep8-1.7.0 py-1.4.31 pyflakes-1.2.3 pytest-2.8.7 pytest-cache-1.0 pytest-cov-1.8.1 vcrpy-1.9.0 wrapt-1.10.11
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container d3de74b42318
 ---> 03828704d1b5
Step 10/11 : ADD . /app
 ---> c8cf345dfc53
Step 11/11 : WORKDIR /app
 ---> Running in ed2fc8b17be3
Removing intermediate container ed2fc8b17be3
 ---> d3aa3b3d0df1
Successfully built d3aa3b3d0df1
Successfully tagged liberapaycom_web:latest
```

But the `docker-compose up` fails:

```
$ docker-compose up
Starting liberapaycom_db_1 ... done
Recreating liberapaycom_web_1 ... done
Attaching to liberapaycom_db_1, liberapaycom_web_1
db_1   | LOG:  database system was shut down at 2018-09-14 12:16:37 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
web_1  | [2018-10-30 06:38:47 +0000] [9] [INFO] Starting gunicorn 19.6.0
web_1  | [2018-10-30 06:38:47 +0000] [9] [INFO] Listening at: http://0.0.0.0:8339 (9)
web_1  | [2018-10-30 06:38:47 +0000] [9] [INFO] Using worker: sync
web_1  | [2018-10-30 06:38:47 +0000] [13] [INFO] Booting worker with pid: 13
web_1  | [2018-10-30 06:38:47 +0000] [15] [INFO] Booting worker with pid: 15
web_1  | [2018-10-30 06:38:52 +0000] [13] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 123, in <module>
web_1  |     if conf.ses_feedback_queue_url:
web_1  | AttributeError: 'AppConf' object has no attribute 'ses_feedback_queue_url'
web_1  | [2018-10-30 06:38:52 +0000] [13] [INFO] Worker exiting (pid: 13)
web_1  | [2018-10-30 06:38:52 +0000] [15] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 123, in <module>
web_1  |     if conf.ses_feedback_queue_url:
web_1  | AttributeError: 'AppConf' object has no attribute 'ses_feedback_queue_url'
web_1  | Won't log to Sentry (SENTRY_DSN is empty).
web_1  | Missing configuration variables:  ses_feedback_queue_url paypal_id smtp_username paypal_domain ses_region smtp_use_tls smtp_port fetch_email_bounces_every smtp_password smtp_host check_email_domains paypal_secret
web_1  | [2018-10-30 06:38:52 +0000] [15] [INFO] Worker exiting (pid: 15)
web_1  | Won't log to Sentry (SENTRY_DSN is empty).
web_1  | Missing configuration variables:  ses_feedback_queue_url paypal_id smtp_username paypal_domain ses_region smtp_use_tls smtp_port fetch_email_bounces_every smtp_password smtp_host check_email_domains paypal_secret
db_1   | LOG:  unexpected EOF on client connection with an open transaction
db_1   | LOG:  unexpected EOF on client connection with an open transaction
db_1   | LOG:  unexpected EOF on client connection with an open transaction
web_1  | [2018-10-30 06:39:22 +0000] [9] [INFO] Shutting down: Master
web_1  | [2018-10-30 06:39:22 +0000] [9] [INFO] Reason: Worker failed to boot.
liberapaycom_web_1 exited with code 3
```

I would be a good idea to check that the docker build is not broken during CI.

**Comment by Changaco** [comment] 2018-10-30 07:48
> It would be a good idea to check that the docker build is not broken during CI.

Hell no. Docker is heavy and isn't officially supported. Moreover this issue has nothing to do with Docker.

**Comment by Changaco** [comment] 2018-10-30 08:12
Closing because I fixed this bug a month ago in 011fc36c7fd12461c3eccb4b2ca0955b5e3d7a73.

**Comment by Changaco** [comment] 2018-10-30 11:53
I think you got this error because the Docker setup doesn't automatically run the DB migrations.

**Comment by MartinDelille** [comment] 2018-11-01 13:40
Ok so there is a bug on the Docker setup. I personnally use Docker because it's convenient: with two lines we have a local instance up and running. I will reopen and rename this issue.

**Comment by Changaco** [comment] 2018-11-07 10:50
Docker is slow and uses a lot of space because it's designed to achieve total consistency and reproducibility, not to facilitate the efficient installation of software.

The alternative is to simply not use Docker. The only dependency that isn't managed automatically is PostgreSQL, and it's not that hard to set up a PostgreSQL server, but clearly it's too complicated or otherwise problematic for some people so we should probably automate it instead of only having instructions in the README.

**Comment by MartinDelille** [comment] 2018-11-07 11:02
+1 for PostgreSQL automation: Each time I try to update my dev environment I have some issue with the database.

What about implementing the good practice described in the article? https://githubengineering.com/scripts-to-rule-them-all/

**Comment by techtonik** [comment] 2019-09-04 05:55
Newest error message about migrations I guess.
```
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 350, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 105, in <module>
web_1  |     d = wireup.full_algorithm.run(**website.__dict__)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/algorithm.py", line 342, in run
web_1  |     loop(False)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/algorithm.py", line 333, in loop
web_1  |     loop(True)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/algorithm.py", line 321, in loop
web_1  |     new_state = function(**deps.as_kwargs)
web_1  |   File "/app/liberapay/wireup.py", line 137, in database
web_1  |     db.register_model(model)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 656, in register_model
web_1  |     raise NoSuchType(typname)
web_1  | postgres.NoSuchType: You tried to register an orm model for typname elsewhere, but no such type exists in the pg_type table of your database.
web_1  | [2019-09-04 05:52:41 +0000] [10] [INFO] Worker exiting (pid: 10)
```

**Comment by Changaco** [comment] 2021-01-22 12:12
Closing in favor of #1962.

**Closed by Changaco** 2021-01-22 12:12 UTC
Labels: DevX
