### ISSUE TITLE
New feature: favourite profiles

### ISSUE THREAD

**Issue by eldelacajita** [liberapay/liberapay.com#1144] opened 2018-06-14 10:24 UTC
This is more a suggestion/discussion than a bug. 

To navigate the diversity of profiles present in Liberapay, I would love to be able to "mark as favorite" certain profiles of people, groups or organizations. I use the "follow" function on Patreon as it allows you to keep track of someone's work even if you are not donating to them right now. It is useful, for example, if you are still considering whether you should contribute to their project or not. But "following" someone in Liberapay doesn't make sense because there is no regular updates feature in the platform. 

I have found a personal workaround for this: If I'm interested in someone's work and am still considering donating, or just want to keep track of them, I just donate 0,01€, so I can see their profile in my "donating to" list. 

This works, and has some interesting qualities (pushing myself to just donate a little instead of just following) but it feels like what it is: a workaround. 

Could it make sense to add a "favorite" or "star" in Liberapay?
Could it make sense to link that action to a symbolic donation, by design and by philosophy?

**Comment by Changaco** [comment] 2018-06-14 10:58
This issue is a duplicate of #48.

The issue for the "follow" feature is #41.

**Comment by eldelacajita** [comment] 2018-06-14 12:08
Sorry again, I'll have to try and search for several related terms before filing a new bug. I guess we can close this one.

**Closed** 2018-06-14 12:10 UTC
