### ISSUE TITLE
[Feature Request] Profile Banner

### ISSUE THREAD

**Issue by MrTeeXD** [liberapay/liberapay.com#1590] opened 2019-10-04 08:52 UTC
Hello. I really like LiberaPay and I want it to grow. May i suggest a Profile Banner where you can create a 1200x600 Image and then put it as your banner? It would be great.

**Comment by Changaco** [comment] 2019-10-04 09:10
This issue is a duplicate of #735.

**Closed by Changaco** 2019-10-04 09:10 UTC
