### ISSUE TITLE
Linking Mastodon account fails for certain Mastodon configurations

### ISSUE THREAD

**Issue by bbliem** [liberapay/liberapay.com#2267] opened 2023-08-02 22:14 UTC
Some Mastodon servers are configured so that user handles look like `@alice@example.com`, whereas the Mastodon server is actually reachable at `https://mastodon.example.com`. This is an [officially documented way](https://docs.joinmastodon.org/admin/config/#local_domain) of configuring Mastodon.

Trying to link such an account to Liberapay results in the error: "Is example.com really a Mastodon server? It is currently not acting like one."

The reason this fails is the following conditional in `liberapay/elsewhere/_base.py`:

```python
        if not self.x_user_id:
            r.user_id = r.user_name
        elif source == r.domain:
            r.user_id = self.x_user_id(r, info)
        else:
            r.user_id = None
```

In a case as described, the `elif` branch would test for `'example.com' == 'mastodon.example.com'`, which is false, causes `r.user_id` to be `None` and later causes the exception to be raised.

Is the test for `source == r.domain` really needed? I'm not sure at the moment how to fix this without potentially breaking other OAuth platforms. Please let me know if I can help you with some more information.

**Comment by Changaco** [comment] 2023-08-03 06:42
This issue is a duplicate of #945.

**Closed by Changaco** 2023-08-03 06:42 UTC
