### ISSUE TITLE
Error docker-compose run web python and docker-compose up

### ISSUE THREAD

**Issue by elbakkayg** [liberapay/liberapay.com#1636] opened 2019-12-24 13:18 UTC
when populate the database with fake data with command "docker-compose run web python -m liberapay.utils.fake_data". I have the message : 

Starting liberapaycom_db_1 ... done
/bin/sh: 1: python: not found

when i launch docker-compose up : 

Starting liberapaycom_db_1 ... done
Starting liberapaycom_web_1 ... done
Attaching to liberapaycom_db_1, liberapaycom_web_1
db_1   | 
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   | 
db_1   | LOG:  database system was shut down at 2019-12-24 13:13:21 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
web_1  | [2019-12-24 13:13:34 +0000] [7] [INFO] Starting gunicorn 19.9.0
web_1  | [2019-12-24 13:13:34 +0000] [7] [INFO] Listening at: http://0.0.0.0:8339 (7)
web_1  | [2019-12-24 13:13:34 +0000] [7] [INFO] Using worker: sync
web_1  | [2019-12-24 13:13:34 +0000] [10] [INFO] Booting worker with pid: 10
web_1  | [2019-12-24 13:13:34 +0000] [12] [INFO] Booting worker with pid: 12
web_1  | /usr/local/lib/python3.7/dist-packages/aspen/renderers.py:8: FutureWarning: aspen.renderers is deprecated and will be removed in a future version. Please use aspen.simplates.renderers instead.
web_1  |   'Please use aspen.simplates.renderers instead.', FutureWarning)
web_1  | [2019-12-24 13:13:36 +0000] [10] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 659, in _from_db
web_1  |     caster = super(ModelCaster, cls)._from_db(name, cursor)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/psycopg2/extras.py", line 1119, in _from_db
web_1  |     "PostgreSQL type '%s' not found" % name)
web_1  | psycopg2.ProgrammingError: PostgreSQL type 'elsewhere' not found
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 350, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 109, in <module>
web_1  |     d = wireup.full_chain.run(**dict(website.__dict__, **rp.__dict__))
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 349, in run
web_1  |     loop(False)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 340, in loop
web_1  |     loop(True)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 328, in loop
web_1  |     new_state = function(**deps.as_kwargs)
web_1  |   File "/app/liberapay/wireup.py", line 148, in database
web_1  |     db.register_model(model)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 521, in register_model
web_1  |     caster = ModelCaster._from_db(self, typname, ModelSubclass)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 661, in _from_db
web_1  |     raise NoSuchType(typname)
web_1  | postgres.NoSuchType: You tried to register an orm model for typname elsewhere, but no such type exists in the pg_type table of your database.
web_1  | [2019-12-24 13:13:36 +0000] [10] [INFO] Worker exiting (pid: 10)
web_1  | Won't log to Sentry (SENTRY_DSN is empty).
web_1  | /usr/local/lib/python3.7/dist-packages/aspen/renderers.py:8: FutureWarning: aspen.renderers is deprecated and will be removed in a future version. Please use aspen.simplates.renderers instead.
web_1  |   'Please use aspen.simplates.renderers instead.', FutureWarning)
web_1  | [2019-12-24 13:13:36 +0000] [12] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 659, in _from_db
web_1  |     caster = super(ModelCaster, cls)._from_db(name, cursor)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/psycopg2/extras.py", line 1119, in _from_db
web_1  |     "PostgreSQL type '%s' not found" % name)
web_1  | psycopg2.ProgrammingError: PostgreSQL type 'elsewhere' not found
web_1  | 
web_1  | During handling of the above exception, another exception occurred:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 350, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 109, in <module>
web_1  |     d = wireup.full_chain.run(**dict(website.__dict__, **rp.__dict__))
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 349, in run
web_1  |     loop(False)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 340, in loop
web_1  |     loop(True)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/state_chain.py", line 328, in loop
web_1  |     new_state = function(**deps.as_kwargs)
web_1  |   File "/app/liberapay/wireup.py", line 148, in database
web_1  |     db.register_model(model)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 521, in register_model
web_1  |     caster = ModelCaster._from_db(self, typname, ModelSubclass)
web_1  |   File "/usr/local/lib/python3.7/dist-packages/postgres/__init__.py", line 661, in _from_db
web_1  |     raise NoSuchType(typname)
web_1  | postgres.NoSuchType: You tried to register an orm model for typname elsewhere, but no such type exists in the pg_type table of your database.
web_1  | [2019-12-24 13:13:36 +0000] [12] [INFO] Worker exiting (pid: 12)
web_1  | Won't log to Sentry (SENTRY_DSN is empty).
web_1  | [2019-12-24 13:13:37 +0000] [7] [INFO] Shutting down: Master
web_1  | [2019-12-24 13:13:37 +0000] [7] [INFO] Reason: Worker failed to boot.
liberapaycom_web_1 exited with code 3

**Comment by Changaco** [comment] 2019-12-24 16:21
Duplicate of #1304.

**Closed by Changaco** 2019-12-24 16:21 UTC
