### ISSUE TITLE
Prevent 401 phishing attacks

### ISSUE THREAD

**Issue by EdOverflow** [liberapay/liberapay.com#504] opened 2017-01-10 15:17 UTC
The following markdown image should prompt you with an authentication dialog:

~~~
![](https://httpbin.org/basic-auth/user/passwd)
~~~

This can be used for 401 phishing attacks, where the credentials are sent to an attackers' server.

**Comment by EdOverflow** [comment] 2017-01-10 15:22
Maybe we should also prevent use of SVG images.

~~~
![](http://brutelogic.com.br/poc.svg) <-- Open this image in a new tab.
~~~

**Comment by Changaco** [comment] 2017-01-10 15:26
Nice find. :-) What solution would you recommend? The only effective one I can think of is to proxy all images. That's pretty much #202.

**Comment by Changaco** [comment] 2017-01-10 15:27
Note that Firefox does show a warning:

> https://httpbin.org is requesting your username and password. WARNING: Your password will not be sent to the website you are currently visiting!

Screenshot:

![spectacle h13774](https://cloud.githubusercontent.com/assets/1581590/21811897/893c17e4-d751-11e6-9ea3-fbe81d0a1c9c.png)

**Comment by Changaco** [comment] 2017-01-10 15:41
Can't we tell the browser not to show the prompt through CSP or a similar mechanism?

Why do browsers even show a prompt in this case? What legitimate use-case is there for this?

**Comment by EdOverflow** [comment] 2017-01-10 15:43
> Why do browsers even show a prompt in this case? What legitimate use-case is there for this?

This is the authentication mechanism for the HTTP Basic Authentication Protocol: http://blog.stevensanderson.com/2008/08/25/using-the-browsers-native-login-prompt/

**Comment by Changaco** [comment] 2017-01-10 15:44
I know what it is, but I see no reason to allow it for images. ;-)

**Comment by EdOverflow** [comment] 2017-01-10 15:51
Oh, sorry. There isn't really a legitimate use of this mechanism in images. For some reason developers are not interested in fixing this issue.

The only real solution is to proxy all images as suggested in #202.

**Comment by Changaco** [comment] 2017-01-10 15:54
> For some reason developers are not interested in fixing this issue.

Do you have links to the relevant tickets in the bug trackers of browsers?

**Comment by EdOverflow** [comment] 2017-01-10 15:57
> Do you have links to the relevant tickets in the bug trackers of browsers?

https://bugs.chromium.org/p/chromium/issues/detail?id=21628

> Can't we tell the browser not to show the prompt through CSP or a similar mechanism?

I will look into this. There is a discussion concerning a CSP implementation here: https://www.w3.org/2011/webappsec/track/issues/68

**Comment by Changaco** [comment] 2017-01-10 16:15
Looks like it's not considered in scope for CSP (quote from your link: "it doesn't belong in CSP"), and since there is no spec saying that it shouldn't be allowed the behavior of browsers hasn't been changed.

**Comment by EdOverflow** [comment] 2017-01-10 16:17
Yep, I am with you on that. :)

**Comment by Changaco** [comment] 2017-01-10 16:41
Mozilla ticket: [647010 – Only present HTTP authentication dialogs if it is the top-level document initiating the auth](https://bugzilla.mozilla.org/show_bug.cgi?id=647010).

**Comment by Changaco** [comment] 2017-01-16 10:41
The new [`SaferHtmlRenderer`](http://misaka.61924.nl/#misaka.SaferHtmlRenderer) that I've contributed to Misaka has built-in support for URL rewriting.

**Comment by Changaco** [comment] 2017-01-24 22:31
Relevant article: [GitHub’s post-CSP journey](https://githubengineering.com/githubs-post-csp-journey/).

**Comment by Changaco** [comment] 2017-01-31 16:04
[camo: an http proxy to route images through SSL](https://github.com/atmos/camo) (GitHub's image proxy).

**Comment by Changaco** [comment] 2018-03-27 12:04
Cloudflare workers seem like the best way to fix this. It would cost $5 per month.

**Comment by Changaco** [comment] 2020-06-13 07:44
It looks like this issue has been fixed in browsers, I can't reproduce it anymore in Firefox (76.0.1) and Chromium (83.0.4103.61).

**Closed by Changaco** 2020-06-13 07:44 UTC
Labels: Defense
