### ISSUE TITLE
Group avatar doesn't get fetched from Libravatar

### ISSUE THREAD

**Issue by mbridon** [liberapay/liberapay.com#2515] opened 2024-12-13 13:18 UTC
I manage the [Cangjie](https://liberapay.com/cangjie) group on Libearapay and would like to use this image I had made a while ago for it

![cangjie-with-codes](https://github.com/user-attachments/assets/dbae33af-432d-4ffd-a84e-2cb83a70325a)

So I uploaded it to libravatar and associated it to my email address which I use on Liberapay: `bochecha[AT]daitauha.fr`

When I try to use it as the avatar for the Cangjie group I get nothing. :confused:

Also, it's a bit weird that the avatar of a group would be associated with the email address of only one member of the group, but I guess that's how Libravatar works, right? :shrug: 

Uploading a single file as a group avatar would work better IMHO.

**Comment by Changaco** [comment] 2024-12-14 20:19
The image isn't actually associated with your email address on the Libravatar side. (You can see that by going to https://www.libravatar.org/tools/check/ and inputting your email address.)

**Comment by mbridon** [comment] 2024-12-15 09:37
Ok... in that case why when I click on "Modifier votre Libravatar" does Liberapay redirect me to my Libravatar acount for bochecha@daitauha.fr? :confused: 

The interaction between Liberapay and Libravatar is at best incredibly confusing, at worst totally wrong. :confounded: 

Really for teams, the avatar should not be linked to the account of a maintainer, it should be uploaded for the team. :shrug:

**Comment by Changaco** [comment] 2024-12-15 21:33
You've created a Libravatar account with your email address, and uploaded an avatar to that account, but you haven't associated the avatar with the email address, so nobody else can see it.

This issue is a duplicate of #1740, so I'm closing it in favour of #1742.

**Closed by Changaco** 2024-12-15 21:33 UTC
