### ISSUE TITLE
Docker-compose errors at fake data and up

### ISSUE THREAD

**Issue by 1Jesper1** [liberapay/liberapay.com#1516] opened 2019-06-03 19:12 UTC
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
>     mod_name, _Error)
>   File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
>     loader = get_loader(mod_name)
>   File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
>     return find_loader(fullname)
>   File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
>     for importer in iter_importers(fullname):
>   File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
>     __import__(pkg)
>   File "liberapay/utils/__init__.py", line 267
> SyntaxError: Non-ASCII character '\xe2' in file liberapay/utils/__init__.py on line 267, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

> [2019-06-03 19:09:58 +0000] [11] [ERROR] Non-ASCII character '\xe2' in file /app/liberapay/main.py on line 324, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (main.py, line 324)
> web_1  | Traceback (most recent call last):
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
> web_1  |     self.wsgi = self.app.wsgi()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
> web_1  |     self.callable = self.load()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
> web_1  |     return self.load_wsgiapp()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
> web_1  |     return util.import_app(self.app_uri)
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 350, in import_app
> web_1  |     __import__(module)
> web_1  |   File "/app/liberapay/main.py", line 324
> web_1  | SyntaxError: Non-ASCII character '\xe2' in file /app/liberapay/main.py on line 324, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> web_1  | [2019-06-03 19:09:58 +0000] [13] [INFO] Booting worker with pid: 13
> web_1  | [2019-06-03 19:09:58 +0000] [13] [ERROR] Non-ASCII character '\xe2' in file /app/liberapay/main.py on line 324, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (main.py, line 324)
> web_1  | Traceback (most recent call last):
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
> web_1  |     self.wsgi = self.app.wsgi()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
> web_1  |     self.callable = self.load()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
> web_1  |     return self.load_wsgiapp()
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
> web_1  |     return util.import_app(self.app_uri)
> web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 350, in import_app
> web_1  |     __import__(module)
> web_1  |   File "/app/liberapay/main.py", line 324
> web_1  | SyntaxError: Non-ASCII character '\xe2' in file /app/liberapay/main.py on line 324, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by mattbk** [comment] 2019-06-06 17:03
It looks like encoding is declared on [some files but not others](https://github.com/liberapay/liberapay.com/search?q=encoding&unscoped_q=encoding). 

Have you tried adding `# encoding: utf8` to the top of those two files?

**Comment by mattbk** [comment] 2019-06-26 16:54
Also, can you share your docker-compose file?

**Comment by 1Jesper1** [comment] 2019-06-27 08:09
@mattbk https://github.com/liberapay/liberapay.com/blob/master/docker-compose.yml

**Comment by techtonik** [comment] 2019-09-04 05:51
Python 3 is not used anymore, so this becomes a duplicate of #1304. :b

**Closed** 2019-09-06 12:26 UTC
