### ISSUE TITLE
Stats broken on mobile

### ISSUE THREAD

**Issue by revi** [liberapay/liberapay.com#626] opened 2017-06-30 10:40 UTC
Device is iPhone 6s.

Screenshot should be explaining everything by itself.

![img_1380](https://user-images.githubusercontent.com/7630875/27732308-96efc0ec-5dcb-11e7-9993-d741f45d512c.PNG)

**Comment by Changaco** [comment] 2017-06-30 10:56
Thanks for the report. Closing as duplicate of #552.

**Closed by Changaco** 2017-06-30 10:56 UTC
