### ISSUE TITLE
Cannot use email which ends in ".xyz"

### ISSUE THREAD

**Issue by Jackojc** [liberapay/liberapay.com#1517] opened 2019-06-04 21:01 UTC
My email is of the form me@website.xyz and Liberapay doesn't seem to like the extension when I go to add it my account.

**Comment by Changaco** [comment] 2019-06-05 08:10
The problem isn't the TLD. (As of now we have 49 email addresses ending in `.xyz` connected to Liberapay accounts.)

The problem is that your domain doesn't have an MX record. Consequently I'm closing this issue as a duplicate of #1480.

**Closed by Changaco** 2019-06-05 08:10 UTC

**Comment by Jackojc** [comment] 2019-06-05 16:56
Ah yes, you are correct. Thanks for the help regardless, is it possible the error popup could be reworded or amended to include what you mentioned about incorrect MX records?
