### ISSUE TITLE
"Your request has been rejected by our software"

### ISSUE THREAD

**Issue by karan** [liberapay/liberapay.com#1730] opened 2020-04-08 23:58 UTC
On login, I keep getting this error:

```
URL: https://liberapay.com/~1609406/giving/
Method: POST
Referer: b'https://liberapay.com/~1609406/giving/'
Response code: 403
Response message: 'A security check has failed. Please make sure your browser is configured to allow cookies for liberapay.com, then try again.'
```

I have tried Android and Mac OS with Brave (Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)), and have tried with all cookies enabled (including 3rd party cookies).

**Comment by carakas** [comment] 2020-04-09 06:31
Same report here

**Comment by Changaco** [comment] 2020-04-09 06:46
I've found the problem and I should be able to fix it soon. In the meantime the workaround is to log in via <https://liberapay.com/log-in>.

**Comment by Changaco** [comment] 2020-04-09 07:18
This is now fixed in production. I'm working on a proper patch including a regression test.

**Comment by karan** [comment] 2020-04-09 17:28
Still seeing the same from the log-in page

```
URL: https://liberapay.com/log-in
Method: POST
Referer: b'https://liberapay.com/log-in'
Response code: 403
Response message: 'A security check has failed. Please make sure your browser is configured to allow cookies for liberapay.com, then try again.'
```

**Comment by Changaco** [comment] 2020-04-09 19:23
If you have to allow 3rd party cookies for it to work, then that's a browser bug, because our cookies aren't 3rd party (they're for `.liberapay.com`, which means "liberapay.com and its subdomains").

**Closed** 2020-04-10 06:56 UTC
Labels: Bug
