### ISSUE TITLE
SUGGESTION: Progressive Web App for Liberapay

### ISSUE THREAD

**Issue by Tagby76** [liberapay/liberapay.com#2214] opened 2023-02-01 03:30 UTC
Salutations! 

I cannot find an Android/iOS app for liberapay. I don't know if this topic has been talked about already, But I think it would be really cool for mobile users if Liberapay was turned into a progressive web app.

I don't know how much work that would take versus making an app from scratch for Android and iOS.

Does the team have any plans for a PWA in the future?

**Comment by Changaco** [comment] 2023-02-01 10:34
This issue is a duplicate of #1000. You can work on it yourself if you have the time and skills.

**Closed by Changaco** 2023-02-01 10:34 UTC
