### ISSUE TITLE
"Add Money" amounts incorrect

### ISSUE THREAD

**Issue by Ben-Waters** [liberapay/liberapay.com#1124] opened 2018-06-01 16:31 UTC
**Initial setup**
Giving €68.77 per month spread across 14 different recipients
Pledging €106.43 per month across 8 different potential recipients

![donations](https://user-images.githubusercontent.com/932966/40851994-0798d850-6597-11e8-81e5-7c79162ebf68.png)
![pledges](https://user-images.githubusercontent.com/932966/40852033-2457f1ec-6597-11e8-9095-1d20d30cbe5a.png)

**The Issue**
Based on the above data I would expect 1 month of donations to cost €68.77 + 2.23% but when I go to add money it suggests that 1 month will cost €165.41.

**Steps to Reproduce**

1. Setup your giving similar to above

1. From the 'Giving' screen click the 'Add money' button

1. Choose to add by 'Credit or Debit card' 

![incorrect-amounts](https://user-images.githubusercontent.com/932966/40852202-b51530aa-6597-11e8-813c-a7467ac92ca4.png)

**Comment by Changaco** [comment] 2018-06-01 16:36
This issue is a duplicate of #1065.

**Closed** 2018-06-01 20:45 UTC
