### ISSUE TITLE
being able to add self hosted gitlab instances as linked accounts

### ISSUE THREAD

**Issue by tsdgeos** [liberapay/liberapay.com#1835] opened 2020-08-02 00:11 UTC
If i link https://invent.kde.org/aacid it is more splashy than https://github.com/tsdgeos or https://gitlab.com/tsdgeos

Is that something that's doable or needs support in each and every self hosted instance?

**Comment by Changaco** [comment] 2020-08-02 07:01
This issue is a duplicate of #661.

**Closed by Changaco** 2020-08-02 07:01 UTC
