### ISSUE TITLE
Join a team notification bug

### ISSUE THREAD

**Issue by RomainLalande** [liberapay/liberapay.com#208] opened 2016-03-08 09:16 UTC
Hello,
I had a invitation to join a team, the notification continue to be displayed. And if I accept again i can see an error message "You have already accepted this invitation.".

FR :J'ai une invitation à une team qui s'affiche alors que je l'ai déjà acceptée, elle ne veut pas ne plus s'afficher. 

Romain

**Comment by Changaco** [comment] 2016-03-08 09:33
This is a duplicate of #133. Our notifications suck right now, sorry. We have [a milestone](https://github.com/liberapay/liberapay.com/milestones/Notifications) about fixing notifications.

**Closed by Changaco** 2016-03-08 09:33 UTC
